
/*
  ____  ____  _  _  ____  __  __  ___
 (  _ \(_  _)( \/ )(  _ \(  \/  )/ __)
  )(_) )_)(_  \  /  ) _ < )    ( \__ \
 (____/(____) (__) (____/(_/\/\_)(___/

DIYBMS V4.0
ESP8266 MODULE

(c)2019 Stuart Pittaway

COMPILE THIS CODE USING PLATFORM.IO

LICENSE
Attribution-NonCommercial-ShareAlike 2.0 UK: England & Wales (CC BY-NC-SA 2.0 UK)
https://creativecommons.org/licenses/by-nc-sa/2.0/uk/

* Non-Commercial — You may not use the material for commercial purposes.
* Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made.
  You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
* ShareAlike — If you remix, transform, or build upon the material, you must distribute your   contributions under the same license as the original.
* No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
*/

#include <ESPAsyncWebServer.h>
#include <ArduinoJson.h>
#include "FS.h"

#include <SPIFFS.h>
#include "time.h"

#include "defines.h"
#include "DIYBMSServer.h"
#include "EmbeddedFiles_AutoGenerated.h"
#include "EmbeddedFiles_Integrity.h"
#include "Modbus.h"

#include "settings.h"

AsyncWebServer *DIYBMSServer::_myserver;
String DIYBMSServer::UUIDString;

sdcard_info (*DIYBMSServer::_sdcardcallback)() = 0;
void (*DIYBMSServer::_sdcardaction_callback)(uint8_t action) = 0;
PacketRequestGenerator *DIYBMSServer::_prg = 0;
PacketReceiveProcessor *DIYBMSServer::_receiveProc = 0;
diybms_eeprom_settings *DIYBMSServer::_mysettings = 0;
Rules *DIYBMSServer::_rules = 0;
ControllerState *DIYBMSServer::_controlState = 0;
ModbusInfo (*DIYBMSServer::_ModBus)[MODBUS_NUM] = 0;
ModbusVal (*DIYBMSServer::_ModBusVal)[MODBUS_NUM] = 0;
//uint16_t DIYBMSServer::ConfigHasChanged=0;

#define REBOOT_COUNT_DOWN 2000

String DIYBMSServer::uuidToString(uint8_t *uuidLocation)
{
  String string = "";
  int i;
  for (i = 0; i < 16; i++)
  {
    if (i == 4)
      string += "-";
    if (i == 6)
      string += "-";
    if (i == 8)
      string += "-";
    if (i == 10)
      string += "-";
    int topDigit = uuidLocation[i] >> 4;
    int bottomDigit = uuidLocation[i] & 0x0f;
    // High hex digit
    string += "0123456789abcdef"[topDigit];
    // Low hex digit
    string += "0123456789abcdef"[bottomDigit];
  }

  return string;
}

void DIYBMSServer::generateUUID()
{
  //SERIAL_DEBUG.print("generateUUID=");
  byte uuidNumber[16]; // UUIDs in binary form are 16 bytes long

  //ESP32 has inbuilt random number generator
  //https://techtutorialsx.com/2017/12/22/esp32-arduino-random-number-generation/
  for (uint8_t x = 0; x < 16; x--)
    uuidNumber[x] = random(0xFF);

  UUIDString = uuidToString(uuidNumber);
}

bool DIYBMSServer::validateXSS(AsyncWebServerRequest *request)
{
  if (request->hasHeader("Cookie"))
  {
    AsyncWebHeader *cookie = request->getHeader("Cookie");
    if (cookie->value().startsWith("DIYBMS_XSS="))
    {
      if (cookie->value().substring(11).equals(DIYBMSServer::UUIDString))
      {
        if (request->hasParam("xss", true))
        {
          AsyncWebParameter *p1 = request->getParam("xss", true);

          if (p1->value().equals(DIYBMSServer::UUIDString) == true)
          {
            return true;
          }
        }
      }
    }
  }
  request->send(500, "text/plain", "XSS invalid");
  return false;
}

void DIYBMSServer::SendSuccess(AsyncWebServerRequest *request)
{
  AsyncResponseStream *response = request->beginResponseStream("application/json");
  StaticJsonDocument<100> doc;
  doc["success"] = true;
  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::SendFailure(AsyncWebServerRequest *request)
{
  request->send(500, "text/plain", "Failed");
}

void DIYBMSServer::sdMount(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  (*DIYBMSServer::_sdcardaction_callback)(1);

  SendSuccess(request);
}
void DIYBMSServer::sdUnmount(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  (*DIYBMSServer::_sdcardaction_callback)(0);

  SendSuccess(request);
}

void DIYBMSServer::resetCounters(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  //Ask modules to reset bad packet counters
  _prg->sendBadPacketCounterReset();
  _prg->sendResetBalanceCurrentCounter();

  for (uint8_t i = 0; i < maximum_controller_cell_modules; i++)
  {
    cmi[i].badPacketCount = 0;
    cmi[i].PacketReceivedCount = 0;
  }

  //Reset internal counters on CONTROLLER
  _receiveProc->ResetCounters();

  _prg->packetsGenerated = 0;

  SendSuccess(request);
}

void DIYBMSServer::saveDisplaySetting(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  if (request->hasParam("VoltageHigh", true))
  {
    AsyncWebParameter *p1 = request->getParam("VoltageHigh", true);
    _mysettings->graph_voltagehigh = p1->value().toFloat();
  }

  if (request->hasParam("VoltageLow", true))
  {
    AsyncWebParameter *p1 = request->getParam("VoltageLow", true);
    _mysettings->graph_voltagelow = p1->value().toFloat();
  }

  //Validate high is greater than low
  if (_mysettings->graph_voltagelow > _mysettings->graph_voltagehigh)
  {
    _mysettings->graph_voltagelow = 0;
  }

  saveConfiguration();

  SendSuccess(request);
}

void DIYBMSServer::saveInfluxDBSetting(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  if (request->hasParam("influxEnabled", true))
  {
    AsyncWebParameter *p1 = request->getParam("influxEnabled", true);
    _mysettings->influxdb_enabled = p1->value().equals("on") ? true : false;
  }
  else
  {
    _mysettings->influxdb_enabled = false;
  }

  if (request->hasParam("influxPort", true))
  {
    AsyncWebParameter *p1 = request->getParam("influxPort", true);
    _mysettings->influxdb_httpPort = p1->value().toInt();
  }

  if (request->hasParam("influxServer", true))
  {
    AsyncWebParameter *p1 = request->getParam("influxServer", true);
    p1->value().toCharArray(_mysettings->influxdb_host, sizeof(_mysettings->influxdb_host));
  }

  if (request->hasParam("influxDatabase", true))
  {
    AsyncWebParameter *p1 = request->getParam("influxDatabase", true);
    p1->value().toCharArray(_mysettings->influxdb_database, sizeof(_mysettings->influxdb_database));
  }

  if (request->hasParam("influxUsername", true))
  {
    AsyncWebParameter *p1 = request->getParam("influxUsername", true);
    p1->value().toCharArray(_mysettings->influxdb_user, sizeof(_mysettings->influxdb_user));
  }

  if (request->hasParam("influxPassword", true))
  {
    AsyncWebParameter *p1 = request->getParam("influxPassword", true);
    p1->value().toCharArray(_mysettings->influxdb_password, sizeof(_mysettings->influxdb_password));
  }

  saveConfiguration();

  //ConfigHasChanged = REBOOT_COUNT_DOWN;
  SendSuccess(request);
}

void DIYBMSServer::saveRuleConfiguration(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  //relaytype
  for (int i = 0; i < RELAY_TOTAL; i++)
  {
    String name = "relaytype";
    name = name + (i + 1);
    if (request->hasParam(name.c_str(), true, false))
    {
      AsyncWebParameter *p1 = request->getParam(name.c_str(), true, false);
      //Default
      _mysettings->relaytype[i] = RelayType::RELAY_STANDARD;
      if (p1->value().equals("Pulse"))
      {
        _mysettings->relaytype[i] = RelayType::RELAY_PULSE;
      }
    }
  }

  //Relay default
  for (int i = 0; i < RELAY_TOTAL; i++)
  {
    String name = "defaultrelay";
    name = name + (i + 1);
    if (request->hasParam(name.c_str(), true, false))
    {
      AsyncWebParameter *p1 = request->getParam(name.c_str(), true, false);
      //Default
      _mysettings->rulerelaydefault[i] = RelayState::RELAY_OFF;
      if (p1->value().equals("On"))
      {
        _mysettings->rulerelaydefault[i] = RelayState::RELAY_ON;
      }
    }
  }

  for (int rule = 0; rule < RELAY_RULES; rule++)
  {

    //TODO: This STRING doesnt work properly if its on a single line!
    String name = "rule";
    name = name + (rule + 1);
    name = name + "value";

    if (request->hasParam(name, true))
    {
      AsyncWebParameter *p1 = request->getParam(name, true);
      _mysettings->rulevalue[rule] = p1->value().toInt();
    }

    //TODO: This STRING doesnt work properly if its on a single line!
    String hname = "rule";
    hname = hname + (rule + 1);
    hname = hname + "hysteresis";
    if (request->hasParam(hname, true))
    {
      AsyncWebParameter *p1 = request->getParam(hname, true);
      _mysettings->rulehysteresis[rule] = p1->value().toInt();
    }

    //Rule/relay processing
    for (int i = 0; i < RELAY_TOTAL; i++)
    {
      //TODO: This STRING doesnt work properly if its on a single line!
      String name = "rule";
      name = name + (rule + 1);
      name = name + "relay";
      name = name + (i + 1);
      if (request->hasParam(name, true))
      {
        AsyncWebParameter *p1 = request->getParam(name, true);
        _mysettings->rulerelaystate[rule][i] = p1->value().equals("X") ? RELAY_X : p1->value().equals("On") ? RelayState::RELAY_ON : RelayState::RELAY_OFF;
      }
    }

    //Reset state of rules after updating the new values
    for (int8_t r = 0; r < RELAY_RULES; r++)
    {
      _rules->rule_outcome[r] = false;
    }
  }

  saveConfiguration();

  SendSuccess(request);
}

void DIYBMSServer::saveStorage(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  if (request->hasParam("loggingEnabled", true))
  {
    AsyncWebParameter *p1 = request->getParam("loggingEnabled", true);
    _mysettings->loggingEnabled = p1->value().equals("on") ? true : false;
  }

  if (request->hasParam("loggingFreq", true))
  {
    AsyncWebParameter *p1 = request->getParam("loggingFreq", true);
    _mysettings->loggingFrequencySeconds = p1->value().toInt();
    //Validate
    if (_mysettings->loggingFrequencySeconds < 15 || _mysettings->loggingFrequencySeconds > 600)
    {
      _mysettings->loggingFrequencySeconds = 15;
    }
  }

  saveConfiguration();

  SendSuccess(request);
}

void DIYBMSServer::saveNTP(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  if (request->hasParam("NTPServer", true))
  {
    AsyncWebParameter *p1 = request->getParam("NTPServer", true);
    p1->value().toCharArray(_mysettings->ntpServer, sizeof(_mysettings->ntpServer));
  }

  if (request->hasParam("NTPZoneHour", true))
  {
    AsyncWebParameter *p1 = request->getParam("NTPZoneHour", true);
    _mysettings->timeZone = p1->value().toInt();
  }

  if (request->hasParam("NTPZoneMin", true))
  {
    AsyncWebParameter *p1 = request->getParam("NTPZoneMin", true);
    _mysettings->minutesTimeZone = p1->value().toInt();
  }

  _mysettings->daylight = false;
  if (request->hasParam("NTPDST", true))
  {
    AsyncWebParameter *p1 = request->getParam("NTPDST", true);
    _mysettings->daylight = p1->value().equals("on") ? true : false;
  }

  saveConfiguration();

  //ConfigHasChanged = REBOOT_COUNT_DOWN;
  SendSuccess(request);
}

void DIYBMSServer::saveBankConfiguration(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  uint8_t totalSeriesModules = 1;
  uint8_t totalBanks = 1;

  if (request->hasParam("totalSeriesModules", true))
  {
    AsyncWebParameter *p1 = request->getParam("totalSeriesModules", true);
    totalSeriesModules = p1->value().toInt();
  }

  if (request->hasParam("totalBanks", true))
  {
    AsyncWebParameter *p1 = request->getParam("totalBanks", true);
    totalBanks = p1->value().toInt();
  }

  if (totalSeriesModules * totalBanks <= maximum_controller_cell_modules)
  {
    _mysettings->totalNumberOfSeriesModules = totalSeriesModules;
    _mysettings->totalNumberOfBanks = totalBanks;
    saveConfiguration();

    SendSuccess(request);
  }
  else
  {
    SendFailure(request);
  }
}

void DIYBMSServer::saveMQTTSetting(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  if (request->hasParam("mqttEnabled", true))
  {
    AsyncWebParameter *p1 = request->getParam("mqttEnabled", true);
    _mysettings->mqtt_enabled = p1->value().equals("on") ? true : false;
  }
  else
  {
    _mysettings->mqtt_enabled = false;
  }

  if (request->hasParam("mqttTopic", true))
  {
    AsyncWebParameter *p1 = request->getParam("mqttTopic", true);
    p1->value().toCharArray(_mysettings->mqtt_topic, sizeof(_mysettings->mqtt_topic));
  }
  else
  {
    sprintf(_mysettings->mqtt_topic, "diybms");
  }

  if (request->hasParam("mqttPort", true))
  {
    AsyncWebParameter *p1 = request->getParam("mqttPort", true);
    _mysettings->mqtt_port = p1->value().toInt();
  }

  if (request->hasParam("mqttServer", true))
  {
    AsyncWebParameter *p1 = request->getParam("mqttServer", true);
    p1->value().toCharArray(_mysettings->mqtt_server, sizeof(_mysettings->mqtt_server));
  }

  if (request->hasParam("mqttUsername", true))
  {
    AsyncWebParameter *p1 = request->getParam("mqttUsername", true);
    p1->value().toCharArray(_mysettings->mqtt_username, sizeof(_mysettings->mqtt_username));
  }

  if (request->hasParam("mqttPassword", true))
  {
    AsyncWebParameter *p1 = request->getParam("mqttPassword", true);
    p1->value().toCharArray(_mysettings->mqtt_password, sizeof(_mysettings->mqtt_password));
  }

  saveConfiguration();

  SendSuccess(request);
}

void DIYBMSServer::saveGlobalSetting(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  if (request->hasParam("BypassOverTempShutdown", true) && request->hasParam("BypassThresholdmV", true))
  {

    AsyncWebParameter *p1 = request->getParam("BypassOverTempShutdown", true);
    _mysettings->BypassOverTempShutdown = p1->value().toInt();

    AsyncWebParameter *p2 = request->getParam("BypassThresholdmV", true);
    _mysettings->BypassThresholdmV = p2->value().toInt();

    saveConfiguration();

    _prg->sendSaveGlobalSetting(_mysettings->BypassThresholdmV, _mysettings->BypassOverTempShutdown);

    uint8_t totalModules = _mysettings->totalNumberOfBanks * _mysettings->totalNumberOfSeriesModules;

    for (uint8_t i = 0; i < totalModules; i++)
    {
      if (cmi[i].valid)
      {
        cmi[i].BypassThresholdmV = _mysettings->BypassThresholdmV;
        cmi[i].BypassOverTempShutdown = _mysettings->BypassOverTempShutdown;
      }
    }

    //Just returns NULL
    SendSuccess(request);
  }
  else
  {
    request->send(500, "text/plain", "Missing parameters");
  }
}

void DIYBMSServer::handleNotFound(AsyncWebServerRequest *request)
{
  request->send(404, "text/plain", "Not found");
}

void DIYBMSServer::saveSetting(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  if (request->hasParam("m", true))
  {
    AsyncWebParameter *module = request->getParam("m", true);
    //Will this overflow?
    uint8_t m = module->value().toInt();

    if (m > maximum_controller_cell_modules)
    {
      request->send(500, "text/plain", "Wrong parameters");
    }
    else
    {

      uint8_t BypassOverTempShutdown = 0xFF;
      uint16_t BypassThresholdmV = 0xFFFF;

      // Resistance of bypass load
      //float LoadResistance = 0xFFFF;
      //Voltage Calibration
      float Calibration = 0xFFFF;
      //Reference voltage (millivolt) normally 2.00mV
      //float mVPerADC = 0xFFFF;
      //Internal Thermistor settings
      //uint16_t Internal_BCoefficient = 0xFFFF;
      //External Thermistor settings
      //uint16_t External_BCoefficient = 0xFFFF;

      if (request->hasParam("BypassOverTempShutdown", true))
      {
        AsyncWebParameter *p1 = request->getParam("BypassOverTempShutdown", true);
        BypassOverTempShutdown = p1->value().toInt();
      }

      if (request->hasParam("BypassThresholdmV", true))
      {
        AsyncWebParameter *p1 = request->getParam("BypassThresholdmV", true);
        BypassThresholdmV = p1->value().toInt();
      }
      if (request->hasParam("Calib", true))
      {
        AsyncWebParameter *p1 = request->getParam("Calib", true);
        Calibration = p1->value().toFloat();
      }

      _prg->sendSaveSetting(m, BypassThresholdmV, BypassOverTempShutdown, Calibration);

      clearModuleValues(m);

      SendSuccess(request);
    }
  }
  else
  {
    request->send(500, "text/plain", "Missing parameters");
  }
}

void DIYBMSServer::clearModuleValues(uint8_t module)
{
  cmi[module].valid = false;
  cmi[module].voltagemV = 0;
  cmi[module].voltagemVMin = 6000;
  cmi[module].voltagemVMax = 0;
  cmi[module].badPacketCount = 0;
  cmi[module].inBypass = false;
  cmi[module].bypassOverTemp = false;
  cmi[module].internalTemp = -40;
  cmi[module].externalTemp = -40;
}

void DIYBMSServer::GetRules(AsyncWebServerRequest *request)
{
  AsyncResponseStream *response =
      request->beginResponseStream("application/json");

  DynamicJsonDocument doc(2048);
  JsonObject root = doc.to<JsonObject>();

  struct tm timeinfo;
  if (!getLocalTime(&timeinfo))
  {
    root["timenow"] = 0;
  }
  else
  {
    root["timenow"] = (timeinfo.tm_hour * 60) + timeinfo.tm_min;
  }

  root["ControlState"] = (*_controlState);

  JsonArray defaultArray = root.createNestedArray("relaydefault");
  for (uint8_t relay = 0; relay < RELAY_TOTAL; relay++)
  {
    switch (_mysettings->rulerelaydefault[relay])
    {
    case RELAY_OFF:
      defaultArray.add(false);
      break;
    case RELAY_ON:
      defaultArray.add(true);
      break;
    default:
      defaultArray.add((char *)0);
      break;
    }
  }

  JsonArray typeArray = root.createNestedArray("relaytype");
  for (uint8_t relay = 0; relay < RELAY_TOTAL; relay++)
  {
    switch (_mysettings->relaytype[relay])
    {
    case RELAY_STANDARD:
      typeArray.add("Std");
      break;
    case RELAY_PULSE:
      typeArray.add("Pulse");
      break;
    default:
      typeArray.add((char *)0);
      break;
    }
  }

  JsonArray bankArray = root.createNestedArray("rules");

  for (uint8_t r = 0; r < RELAY_RULES; r++)
  {
    JsonObject rule = bankArray.createNestedObject();
    rule["value"] = _mysettings->rulevalue[r];
    rule["hysteresis"] = _mysettings->rulehysteresis[r];
    rule["triggered"] = _rules->rule_outcome[r];
    JsonArray data = rule.createNestedArray("relays");

    for (uint8_t relay = 0; relay < RELAY_TOTAL; relay++)
    {
      switch (_mysettings->rulerelaystate[r][relay])
      {
      case RELAY_OFF:
        data.add(false);
        break;
      case RELAY_ON:
        data.add(true);
        break;
      default:
        data.add((char *)0);
        break;
      }
    }
  }

  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::settings(AsyncWebServerRequest *request)
{
  AsyncResponseStream *response =
      request->beginResponseStream("application/json");

  DynamicJsonDocument doc(2048);
  JsonObject root = doc.to<JsonObject>();

  JsonObject settings = root.createNestedObject("settings");

  //settings["Version"] = String(GIT_VERSION);
  //settings["CompileDate"] = String(COMPILE_DATE_TIME);

  settings["totalnumberofbanks"] = _mysettings->totalNumberOfBanks;
  settings["totalseriesmodules"] = _mysettings->totalNumberOfSeriesModules;

  settings["bypassthreshold"] = _mysettings->BypassThresholdmV;
  settings["bypassovertemp"] = _mysettings->BypassOverTempShutdown;

  settings["NTPServerName"] = _mysettings->ntpServer;
  settings["TimeZone"] = _mysettings->timeZone;
  settings["MinutesTimeZone"] = _mysettings->minutesTimeZone;
  settings["DST"] = _mysettings->daylight;

  time_t now;
  if (time(&now))
  {
    settings["now"] = now;
  }

  response->addHeader("Cache-Control", "no-store");

  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::storage(AsyncWebServerRequest *request)
{
  AsyncResponseStream *response =
      request->beginResponseStream("application/json");

  DynamicJsonDocument doc(2048);
  JsonObject root = doc.to<JsonObject>();

  JsonObject settings = root.createNestedObject("storage");

  settings["enabled"] = _mysettings->loggingEnabled;
  settings["frequency"] = _mysettings->loggingFrequencySeconds;

  if (DIYBMSServer::_sdcardcallback != 0)
  {
    //Get data from main.cpp
    sdcard_info info = (*DIYBMSServer::_sdcardcallback)();

    settings["sdcard"] = info.available;
    settings["sdcard_total"] = info.totalkilobytes;
    settings["sdcard_used"] = info.usedkilobytes;

    settings["flash_total"] = info.flash_totalkilobytes;
    settings["flash_used"] = info.flash_usedkilobytes;
  }
  response->addHeader("Cache-Control", "no-store");

  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::integration(AsyncWebServerRequest *request)
{
  AsyncResponseStream *response =
      request->beginResponseStream("application/json");

  DynamicJsonDocument doc(2048);
  JsonObject root = doc.to<JsonObject>();

  JsonObject mqtt = root.createNestedObject("mqtt");
  mqtt["enabled"] = _mysettings->mqtt_enabled;
  mqtt["topic"] = _mysettings->mqtt_topic;
  mqtt["port"] = _mysettings->mqtt_port;
  mqtt["server"] = _mysettings->mqtt_server;
  mqtt["username"] = _mysettings->mqtt_username;
  //We don't output the password in the json file as this could breach security
  //mqtt["password"] =_mysettings->mqtt_password;

  JsonObject influxdb = root.createNestedObject("influxdb");
  influxdb["enabled"] = _mysettings->influxdb_enabled;
  influxdb["port"] = _mysettings->influxdb_httpPort;
  influxdb["server"] = _mysettings->influxdb_host;
  influxdb["database"] = _mysettings->influxdb_database;
  influxdb["username"] = _mysettings->influxdb_user;
  //We don't output the password in the json file as this could breach security
  //influxdb["password"] = _mysettings->influxdb_password;

  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::identifyModule(AsyncWebServerRequest *request)
{
  if (request->hasParam("c", false))
  {
    AsyncWebParameter *cellid = request->getParam("c", false);
    uint8_t c = cellid->value().toInt();

    if (c > _mysettings->totalNumberOfBanks * _mysettings->totalNumberOfSeriesModules)
    {
      request->send(500, "text/plain", "Wrong parameter bank");
      return;
    }
    else
    {
      _prg->sendIdentifyModuleRequest(c);
      SendSuccess(request);
    }
  }
  else
  {
    request->send(500, "text/plain", "Missing parameters");
  }
}

void DIYBMSServer::modules(AsyncWebServerRequest *request)
{
  if (request->hasParam("c", false))
  {
    AsyncWebParameter *cellid = request->getParam("c", false);
    uint8_t c = cellid->value().toInt();

    if (c > _mysettings->totalNumberOfBanks * _mysettings->totalNumberOfSeriesModules)
    {
      request->send(500, "text/plain", "Wrong parameter bank");
      return;
    }

    if (cmi[c].settingsCached == false)
    {
      _prg->sendGetSettingsRequest(c);
    }

    AsyncResponseStream *response = request->beginResponseStream("application/json");

    DynamicJsonDocument doc(2048);
    JsonObject root = doc.to<JsonObject>();
    JsonObject settings = root.createNestedObject("settings");

    uint8_t b = c / _mysettings->totalNumberOfSeriesModules;
    uint8_t m = c - (b * _mysettings->totalNumberOfSeriesModules);
    settings["bank"] = b;
    settings["module"] = m;
    settings["id"] = c;
    settings["ver"] = cmi[c].BoardVersionNumber;
    settings["code"] = cmi[c].CodeVersionNumber;
    settings["Cached"] = cmi[c].settingsCached;

    if (cmi[c].settingsCached)
    {
      settings["BypassOverTempShutdown"] = cmi[c].BypassOverTempShutdown;
      settings["BypassThresholdmV"] = cmi[c].BypassThresholdmV;
      settings["LoadRes"] = cmi[c].LoadResistance;
      settings["Calib"] = cmi[c].Calibration;
      settings["mVPerADC"] = cmi[c].mVPerADC;
      settings["IntBCoef"] = cmi[c].Internal_BCoefficient;
      settings["ExtBCoef"] = cmi[c].External_BCoefficient;
    }

    serializeJson(doc, *response);
    request->send(response);
  }
}

void DIYBMSServer::modbusVal(AsyncWebServerRequest *request)
{

  AsyncResponseStream *response = request->beginResponseStream("application/json");

  DynamicJsonDocument doc(1024);
  JsonObject root = doc.to<JsonObject>();

  JsonArray val = root.createNestedArray("val");
  JsonArray last = root.createNestedArray("last");

  for (int i = 0; i < MODBUS_NUM; i++)
  {
    val.add((*_ModBusVal)[i].val);
    last.add((float)(*_ModBusVal)[i].last / 1000.0);
  }

  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::modbus(AsyncWebServerRequest *request)
{

  AsyncResponseStream *response = request->beginResponseStream("application/json");

  DynamicJsonDocument doc(4096);
  JsonObject root = doc.to<JsonObject>();

  /*
  JsonArray addr = root.createNestedArray("addr");
  JsonArray reg  = root.createNestedArray("reg");
  JsonArray name = root.createNestedArray("name");
  JsonArray unit = root.createNestedArray("unit");
  JsonArray desc = root.createNestedArray("desc");

  for (int i=0; i<MODBUS_NUM; i++) {

    addr.add(ModBus[i].addr);
    reg.add(ModBus[i].reg);
    name.add(ModBus[i].name);
    unit.add(ModBus[i].unit);
    desc.add(ModBus[i].desc);
  }
*/

  JsonArray modbus = root.createNestedArray("modbus");

  const int capacity = JSON_OBJECT_SIZE(100);
  StaticJsonDocument<capacity> obj;

  for (int i = 0; i < MODBUS_NUM; i++)
  {

    obj["dev"] = i;
    obj["addr"] = (*_ModBus)[i].addr;
    obj["reg"] = (*_ModBus)[i].reg;
    obj["min"] = (*_ModBus)[i].min;
    obj["max"] = (*_ModBus)[i].max;
    obj["rule"] = (*_ModBus)[i].rule ? "X" : "";
    obj["mqtt"] = (*_ModBus)[i].mqtt ? "X" : "";
    obj["name"] = (char *)(*_ModBus)[i].name;
    obj["unit"] = (char *)(*_ModBus)[i].unit;
    obj["desc"] = (char *)(*_ModBus)[i].desc;

    modbus.add(obj);
  }

  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::saveModbus(AsyncWebServerRequest *request)
{
  if (!validateXSS(request))
    return;

  int args = request->args();
  for (int i = 0; i < args; i++)
  {
    SERIAL_DEBUG.printf("ARG[%s]: %s\n", request->argName(i).c_str(), request->arg(i).c_str());
  }

  if (request->hasParam("dev", true))
  {
    AsyncWebParameter *device = request->getParam("dev", true);
    //Will this overflow?
    uint8_t d = device->value().toInt();

    if (d >= MODBUS_NUM)
    {
      request->send(500, "text/plain", "Wrong parameters");
    }
    else
    {

      if (request->hasParam("addr", true))
      {
        AsyncWebParameter *p1 = request->getParam("addr", true);
        (*_ModBus)[d].addr = p1->value().toInt();
      }
      if (request->hasParam("reg", true))
      {
        AsyncWebParameter *p1 = request->getParam("reg", true);
        (*_ModBus)[d].reg = p1->value().toInt();
      }
      if (request->hasParam("min", true))
      {
        AsyncWebParameter *p1 = request->getParam("min", true);
        (*_ModBus)[d].min = p1->value().toInt();
      }
      if (request->hasParam("max", true))
      {
        AsyncWebParameter *p1 = request->getParam("max", true);
        (*_ModBus)[d].max = p1->value().toInt();
      }

      if (request->hasParam("name", true))
      {
        AsyncWebParameter *p1 = request->getParam("name", true);
        strncpy((*_ModBus)[d].name, p1->value().c_str(), MODBUS_NAME_LEN);
      }
      if (request->hasParam("unit", true))
      {
        AsyncWebParameter *p1 = request->getParam("unit", true);
        strncpy((*_ModBus)[d].unit, p1->value().c_str(), MODBUS_UNIT_LEN);
      }
      if (request->hasParam("desc", true))
      {
        AsyncWebParameter *p1 = request->getParam("desc", true);
        strncpy((*_ModBus)[d].desc, p1->value().c_str(), MODBUS_DESC_LEN);
      }

      (*_ModBus)[d].rule = request->hasParam("rule", true);
      ESP_LOGD(TAG, "Rule %d\n", (*_ModBus)[d].rule);

      (*_ModBus)[d].mqtt = request->hasParam("mqtt", true);
      ESP_LOGD(TAG, "MQTT %d\n", (*_ModBus)[d].mqtt);

      //      prg.sendSaveSetting(m, BypassThresholdmV, BypassOverTempShutdown, Calibration);

      SendSuccess(request);
    }
  }
  else
  {
    request->send(500, "text/plain", "Missing parameters");
  }
}

/*
Restart controller from web interface
*/
void DIYBMSServer::handleRestartController(AsyncWebServerRequest *request)
{
  ESP.restart();
}

void DIYBMSServer::monitor3(AsyncWebServerRequest *request)
{
  DynamicJsonDocument doc(maximum_controller_cell_modules * 50);

  AsyncResponseStream *response = request->beginResponseStream("application/json");

  //This service exists to ensure that monitor2 is keep as small as possible
  //for ESP8266 memory limitations, these values are only updated very infrequently (lazy timer)
  JsonArray badpacket = doc.createNestedArray("badpacket");
  JsonArray balancecurrentcount = doc.createNestedArray("balcurrent");
  JsonArray packetreceivedcount = doc.createNestedArray("pktrecvd");

  //doc["FreeHeap"] = ESP.getFreeHeap();
  //doc["FreeBlockSize"] = ESP.getMaxFreeBlockSize();

  uint8_t totalModules = _mysettings->totalNumberOfBanks * _mysettings->totalNumberOfSeriesModules;
  for (uint8_t i = 0; i < totalModules; i++)
  {
    if (cmi[i].valid)
    {
      //Just for debug, move these to config packets instead
      balancecurrentcount.add(cmi[i].BalanceCurrentCount);
      packetreceivedcount.add(cmi[i].PacketReceivedCount);
      badpacket.add(cmi[i].badPacketCount);
    }
    else
    {
      //Return NULL
      balancecurrentcount.add((char *)0);
      packetreceivedcount.add((char *)0);
      badpacket.add((char *)0);
    }
  }

  serializeJson(doc, *response);
  request->send(response);
}

void DIYBMSServer::monitor2(AsyncWebServerRequest *request)
{
  //ESP_LOGD(TAG, "monitor2");

  DynamicJsonDocument doc(maximum_controller_cell_modules * 140);

  if (doc.capacity() == 0)
  {
    //If memory allocation fails, swap to a small JSON document
    //so the interface can report the error.
    AsyncResponseStream *response = request->beginResponseStream("application/json");
    DynamicJsonDocument doc2(512);

    doc2["banks"] = _mysettings->totalNumberOfBanks;
    doc2["seriesmodules"] = _mysettings->totalNumberOfSeriesModules;
    JsonArray errors = doc2.createNestedArray("errors");
    //JsonArray warnings = doc2.createNestedArray("warnings");
    errors.add(InternalErrorCode::ControllerMemoryError);
    doc2["sent"] = _prg->packetsGenerated;
    doc2["received"] = _receiveProc->packetsReceived;
    doc2["modulesfnd"] = _receiveProc->totalModulesFound;
    doc2["badcrc"] = _receiveProc->totalCRCErrors;
    doc2["ignored"] = _receiveProc->totalNotProcessedErrors;
    doc2["roundtrip"] = _receiveProc->packetTimerMillisecond;
    doc2["oos"] = _receiveProc->totalOutofSequenceErrors;

    serializeJson(doc2, *response);
    request->send(response);
  }
  else
  {
    AsyncResponseStream *response = request->beginResponseStream("application/json");

    doc["banks"] = _mysettings->totalNumberOfBanks;
    doc["seriesmodules"] = _mysettings->totalNumberOfSeriesModules;
    JsonArray errors = doc.createNestedArray("errors");
    for (size_t i = 0; i < sizeof(_rules->ErrorCodes); i++)
    {
      if (_rules->ErrorCodes[i] != InternalErrorCode::NoError)
      {
        errors.add(_rules->ErrorCodes[i]);
      }
    }

    JsonArray warnings = doc.createNestedArray("warnings");
    for (size_t i = 0; i < sizeof(_rules->WarningCodes); i++)
    {
      if (_rules->WarningCodes[i] != InternalWarningCode::NoWarning)
      {
        warnings.add(_rules->WarningCodes[i]);
      }
    }

    doc["sent"] = _prg->packetsGenerated;
    doc["received"] = _receiveProc->packetsReceived;
    doc["modulesfnd"] = _receiveProc->totalModulesFound;
    doc["badcrc"] = _receiveProc->totalCRCErrors;
    doc["ignored"] = _receiveProc->totalNotProcessedErrors;
    doc["roundtrip"] = _receiveProc->packetTimerMillisecond;
    doc["oos"] = _receiveProc->totalOutofSequenceErrors;

    uint8_t totalModules = _mysettings->totalNumberOfBanks * _mysettings->totalNumberOfSeriesModules;

    JsonArray voltages = doc.createNestedArray("voltages");

    JsonArray minvoltages = doc.createNestedArray("minvoltages");
    JsonArray maxvoltages = doc.createNestedArray("maxvoltages");

    JsonArray bypass = doc.createNestedArray("bypass");
    JsonArray bypasshot = doc.createNestedArray("bypasshot");
    JsonArray inttemp = doc.createNestedArray("inttemp");
    JsonArray exttemp = doc.createNestedArray("exttemp");
    JsonArray bypasspwm = doc.createNestedArray("bypasspwm");

    for (uint8_t i = 0; i < totalModules; i++)
    {
      if (cmi[i].valid)
      {
        voltages.add(cmi[i].voltagemV);

        if (totalModules <= 64)
        {
          //To preserve memory, only return these parameters when there are less than =64 modules
          minvoltages.add(cmi[i].voltagemVMin);
          maxvoltages.add(cmi[i].voltagemVMax);
        }

        if (cmi[i].internalTemp != -40)
        {
          inttemp.add(cmi[i].internalTemp);
        }
        else
        {
          inttemp.add((char *)0);
        }

        if (cmi[i].externalTemp != -40)
        {
          exttemp.add(cmi[i].externalTemp);
        }
        else
        {
          exttemp.add((char *)0);
        }

        bypasspwm.add(cmi[i].inBypass ? cmi[i].PWMValue : 0);
        //Convert boolean to 1 or 0 to save bandwidth (every byte counts on this request)
        bypass.add(cmi[i].inBypass ? 1 : 0);
        bypasshot.add(cmi[i].bypassOverTemp ? 1 : 0);
      }
      else
      {
        //Module is not yet valid so return null values...
        voltages.add((char *)0);
        if (totalModules <= 64)
        {
          minvoltages.add((char *)0);
          maxvoltages.add((char *)0);
          //badpacket.add(0);
        }
        inttemp.add((char *)0);
        exttemp.add((char *)0);
        bypasspwm.add(0);
        //Convert boolean to 1 or 0 to save bandwidth (every byte counts on this request)
        bypass.add(0);
        bypasshot.add(0);
      }
    }

    JsonArray bankvoltage = doc.createNestedArray("bankv");
    JsonArray voltagerange = doc.createNestedArray("voltrange");
    for (uint8_t b = 0; b < _mysettings->totalNumberOfBanks; b++)
    {
      bankvoltage.add(_rules->packvoltage[b]);
      voltagerange.add(_rules->VoltageRangeInBank(b));
    }

    //Current reading in mA
    JsonArray current = doc.createNestedArray("current");
    //current.add(10000);
    //NULL
    current.add((char *)0);

    response->addHeader("Cache-Control", "no-store");

    serializeJson(doc, *response);
    request->send(response);
  }
}

String DIYBMSServer::TemplateProcessor(const String &var)
{
  ESP_LOGD(TAG, "%s", var.c_str());

  if (var == "XSS_KEY")
    return DIYBMSServer::UUIDString;

  if (var == "PLATFORM")
    return String("ESP32");

  if (var == "GIT_VERSION")
    return String(GIT_VERSION);

  if (var == "COMPILE_DATE_TIME")
    return String(COMPILE_DATE_TIME);

  //  const DEFAULT_GRAPH_MAX_VOLTAGE = %graph_voltagehigh%;
  //  const DEFAULT_GRAPH_MIN_VOLTAGE = %graph_voltagelow%;

  if (var == "graph_voltagehigh")
    return String(_mysettings->graph_voltagehigh);

  if (var == "graph_voltagelow")
    return String(_mysettings->graph_voltagelow);

  if (var == "integrity_file_jquery_js")
    return String(integrity_file_jquery_js);

  return String();
}

void DIYBMSServer::SetCacheAndETagGzip(AsyncWebServerResponse *response, String ETag)
{
  response->addHeader("Content-Encoding", "gzip");
  SetCacheAndETag(response, ETag);
}
void DIYBMSServer::SetCacheAndETag(AsyncWebServerResponse *response, String ETag)
{
  response->addHeader("ETag", ETag);
  response->addHeader("Cache-Control", "no-cache, max-age=86400");
}

// Start Web Server (crazy amount of pointer params!)
void DIYBMSServer::StartServer(AsyncWebServer *webserver,
                               diybms_eeprom_settings *mysettings,
                               sdcard_info (*sdcardcallback)(),
                               PacketRequestGenerator *prg,
                               PacketReceiveProcessor *pktreceiveproc,
                               ControllerState *controlState,
                               Rules *rules,
                               ModbusInfo (*ModBus)[MODBUS_NUM],
                               ModbusVal (*ModBusVal)[MODBUS_NUM],
                               void (*sdcardaction_callback)(uint8_t action))
{
  _myserver = webserver;
  _prg = prg;
  _controlState = controlState;
  _rules = rules;
  _sdcardcallback = sdcardcallback;
  _ModBusVal = ModBusVal;
  _ModBus = ModBus;
  _mysettings = mysettings;
  _receiveProc = pktreceiveproc;
  _sdcardaction_callback = sdcardaction_callback;

  String cookieValue = "DIYBMS_XSS=";
  cookieValue += DIYBMSServer::UUIDString;
  cookieValue += String("; path=/; HttpOnly");
  DefaultHeaders::Instance().addHeader("Set-Cookie", cookieValue);

  _myserver->on("/", HTTP_GET, [](AsyncWebServerRequest *request) { request->redirect("/default.htm"); });

  //file_default_htm
  //_myserver->serveStatic("/default.htm", LittleFS, "/default.htm").setTemplateProcessor(DIYBMSServer::TemplateProcessor);
  //_myserver->serveStatic("/", LittleFS, "/").setCacheControl("max-age=600");

  _myserver->on("/default.htm", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  AsyncWebServerResponse *response = request->beginResponse_P(200, "text/html", (char *)file_default_htm, DIYBMSServer::TemplateProcessor);
                  response->addHeader("Cache-Control", "no-store");
                  request->send(response);
                });

  _myserver->on("/pagecode.js", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_pagecode_js_gz)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "application/javascript", file_pagecode_js_gz, size_file_pagecode_js_gz);
                    SetCacheAndETagGzip(response, String(etag_file_pagecode_js_gz));
                    request->send(response);
                  }
                });

  _myserver->on("/favicon.ico", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_favicon_ico_gz)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "image/x-icon", file_favicon_ico_gz, size_file_favicon_ico_gz);
                    SetCacheAndETagGzip(response, String(etag_file_favicon_ico_gz));
                    request->send(response);
                  }
                });

  _myserver->on("/logo.png", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_logo_png)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "image/png", file_logo_png, size_file_logo_png);
                    SetCacheAndETag(response, String(etag_file_logo_png));
                    request->send(response);
                  }
                });

  _myserver->on("/wait.png", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_wait_png)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "image/png", file_wait_png, size_file_wait_png);
                    SetCacheAndETag(response, String(etag_file_wait_png));
                    request->send(response);
                  }
                });

  _myserver->on("/patron.png", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_patron_png)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "image/png", file_patron_png, size_file_patron_png);
                    SetCacheAndETag(response, String(etag_file_patron_png));
                    request->send(response);
                  }
                });

  _myserver->on("/jquery.js", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_jquery_js_gz)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "application/javascript", file_jquery_js_gz, size_file_jquery_js_gz);
                    SetCacheAndETagGzip(response, String(etag_file_jquery_js_gz));
                    request->send(response);
                  }
                });

  _myserver->on("/echarts.min.js", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_echarts_min_js_gz)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "application/javascript", file_echarts_min_js_gz, size_file_echarts_min_js_gz);
                    SetCacheAndETagGzip(response, String(etag_file_echarts_min_js_gz));
                    request->send(response);
                  }
                });

  _myserver->on("/echarts_gl.min.js", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_echarts_gl_min_js_gz)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "application/javascript", file_echarts_gl_min_js_gz, size_file_echarts_gl_min_js_gz);
                    SetCacheAndETagGzip(response, String(etag_file_echarts_gl_min_js_gz));
                    request->send(response);
                  }
                });

  _myserver->on("/style.css", HTTP_GET,
                [](AsyncWebServerRequest *request) {
                  if (request->header("If-None-Match").equals(String(etag_file_style_css_gz)))
                  {
                    request->send(304);
                  }
                  else
                  {
                    AsyncWebServerResponse *response = request->beginResponse_P(200, "text/css", file_style_css_gz, size_file_style_css_gz);
                    SetCacheAndETagGzip(response, String(etag_file_style_css_gz));
                    request->send(response);
                  }
                });

  //Read endpoints
  _myserver->on("/monitor2.json", HTTP_GET, DIYBMSServer::monitor2);
  _myserver->on("/monitor3.json", HTTP_GET, DIYBMSServer::monitor3);
  _myserver->on("/integration.json", HTTP_GET, DIYBMSServer::integration);
  _myserver->on("/modules.json", HTTP_GET, DIYBMSServer::modules);
  _myserver->on("/identifyModule.json", HTTP_GET, DIYBMSServer::identifyModule);
  _myserver->on("/settings.json", HTTP_GET, DIYBMSServer::settings);
  _myserver->on("/rules.json", HTTP_GET, DIYBMSServer::GetRules);
  _myserver->on("/storage.json", HTTP_GET, DIYBMSServer::storage);

  _myserver->on("/modbus.json", HTTP_GET, DIYBMSServer::modbus);
  _myserver->on("/modbusVal.json", HTTP_GET, DIYBMSServer::modbusVal);

  _myserver->on("/savemodbus.json", HTTP_POST, DIYBMSServer::saveModbus);

  //POST method endpoints
  _myserver->on("/savesetting.json", HTTP_POST, DIYBMSServer::saveSetting);
  _myserver->on("/saveglobalsetting.json", HTTP_POST, DIYBMSServer::saveGlobalSetting);
  _myserver->on("/savemqtt.json", HTTP_POST, DIYBMSServer::saveMQTTSetting);
  _myserver->on("/saveinfluxdb.json", HTTP_POST, DIYBMSServer::saveInfluxDBSetting);
  _myserver->on("/savebankconfig.json", HTTP_POST, DIYBMSServer::saveBankConfiguration);
  _myserver->on("/saverules.json", HTTP_POST, DIYBMSServer::saveRuleConfiguration);
  _myserver->on("/saventp.json", HTTP_POST, DIYBMSServer::saveNTP);
  _myserver->on("/savedisplaysetting.json", HTTP_POST, DIYBMSServer::saveDisplaySetting);
  _myserver->on("/savestorage.json", HTTP_POST, DIYBMSServer::saveStorage);

  _myserver->on("/resetcounters.json", HTTP_POST, DIYBMSServer::resetCounters);
  _myserver->on("/restartcontroller.json", HTTP_POST, DIYBMSServer::handleRestartController);

  _myserver->on("/sdmount.json", HTTP_POST, DIYBMSServer::sdMount);
  _myserver->on("/sdunmount.json", HTTP_POST, DIYBMSServer::sdUnmount);

  _myserver->onNotFound(DIYBMSServer::handleNotFound);
  _myserver->begin();

  ESP_LOGD(TAG, "Start Web Server complete");
}
