#ifndef DIYBMSWebServer_Json_Post_H_
#define DIYBMSWebServer_Json_Post_H_

//#include <stdio.h>
//#include <esp_http_server.h>
//#include <WiFi.h>

#include "settings.h"
//#include "FS.h"
//#include <LITTLEFS.h>
//#include "SD.h"
//#include <SPIFFS.h>
//#include "time.h"
//#include "defines.h"
//#include "Rules.h"
//#include "settings.h"
//#include "ArduinoJson.h"
#include "PacketRequestGenerator.h"
#include "PacketReceiveProcessor.h"
//#include "EmbeddedFiles_AutoGenerated.h"
//#include "EmbeddedFiles_Integrity.h"
//#include "HAL_ESP32.h"

esp_err_t post_savebankconfig_json_handler(httpd_req_t *req);
esp_err_t post_saventp_json_handler(httpd_req_t *req);
esp_err_t post_saveglobalsetting_json_handler(httpd_req_t *req);
esp_err_t post_savemqtt_json_handler(httpd_req_t *req);
esp_err_t post_saveinfluxdbsetting_json_handler(httpd_req_t *req);
esp_err_t post_saveconfigurationtosdcard_json_handler(httpd_req_t *req);
esp_err_t post_savewificonfigtosdcard_json_handler(httpd_req_t *req);
esp_err_t post_savesetting_json_handler(httpd_req_t *req);
esp_err_t post_restartcontroller_json_handler(httpd_req_t *req);
esp_err_t post_saverules_json_handler(httpd_req_t *req);
esp_err_t post_savedisplaysetting_json_handler(httpd_req_t *req);
esp_err_t post_savestorage_json_handler(httpd_req_t *req);
esp_err_t post_resetcounters_json_handler(httpd_req_t *req);
esp_err_t post_sdmount_json_handler(httpd_req_t *req);
esp_err_t post_sdunmount_json_handler(httpd_req_t *req);
esp_err_t post_enableavrprog_json_handler(httpd_req_t *req);
esp_err_t post_disableavrprog_json_handler(httpd_req_t *req);
esp_err_t post_avrprog_json_handler(httpd_req_t *req);
esp_err_t post_savers485settings_json_handler(httpd_req_t *req);
esp_err_t post_savecurrentmon_json_handler(httpd_req_t *req);
esp_err_t post_savecmbasic_json_handler(httpd_req_t *req);
esp_err_t post_savecmadvanced_json_handler(httpd_req_t *req);
esp_err_t post_savecmrelay_json_handler(httpd_req_t *req);
esp_err_t post_savevictron_json_handler(httpd_req_t *req);

extern diybms_eeprom_settings *_mysettings;
extern PacketRequestGenerator *_prg;
extern PacketReceiveProcessor *_receiveProc;

extern HAL_ESP32 *_hal;
extern fs::SDFS *_sdcard;

extern uint32_t canbus_messages_received;
extern uint32_t canbus_messages_sent;
extern uint32_t canbus_messages_failed_sent;
extern void (*_sdcardaction_callback)(uint8_t action);
#endif
