// This file is for Russian language translation
// https://www.w3schools.com/tags/ref_language_codes.asp

$("#genericwarning").text("Controller warning ");
$("#warning1").text("Warning: Module bypass voltage is different to global setting");
$("#warning2").text("Warning: Module bypass temperature is different to global setting");
$("#warning3").text("Warning: Modules have mixed versions of code, may cause instability");
$("#warning4").text("Warning: Modules have mixed versions of hardware/boards");
$("#warning5").text("Warning: Logging enabled but SD card not installed/found");
$("#warning6").text("Some features are disabled whilst AVR programming mode enabled");
$("#warning7").text("Web page is unsynchronised with controller, refresh web page (F5)");
$("#sdcardmissing").text("SD card not installed");
$("#error1").text("The controller is having difficulty communicating with the cell monitoring modules.");
$("#error2").text("Controller found  modules, but is configured for .");
$("#error3").text("Controller is configured to use more modules than it can cope with.");
$("#error4").text("Waiting for modules to reply");
$("#error5").text("Module has returned ZERO volt reading, check configuration");
$("#error6").text("Controller has run out of memory.");
$("#error7").text("Emergency Stop");
$("#iperror").text("Cannot communicate with the controller for status updates.");
$("#genericerror").text("Controller error ");
$("#jslibrary").text("Javascript library has failed to load correctly, please refresh page.");
$("#saveerror").text("Failed to save settings.");
$("label[for='ModuleId'").text("Module Id");
$("label[for='Version'").text("Module version");
$("label[for='BypassOverTempShutdown'").text("Bypass over temperature");
$("label[for='BypassThresholdmV'").text("Bypass threshold mV");
$("label[for='Calib'").text("Calibration multiplier");
$("label[for='ActualVoltage'").text("Calculator - Actual measured voltage");
$("label[for='ExtBCoef'").text("External temperature BCoef");
$("label[for='IntBCoef'").text("Internal temperature BCoef");
$("label[for='LoadRes'").text("Load resistance");
$("label[for='mVPerADC'").text("mV per ADC reading");
$("label[for='g1'").text("Bypass over temperature");
$("label[for='g2'").text("Bypass threshold mV");
$("label[for='mqttEnabled'").text("Enabled");
$("label[for='mqttTopic'").text("Topic");
$("label[for='mqttServer'").text("Server");
$("label[for='mqttPort'").text("Port");
$("label[for='mqttUsername'").text("Username");
$("label[for='mqttPassword'").text("Password");
$("label[for='influxEnabled'").text("Enabled");
$("label[for='influxServer'").text("Host server");
$("label[for='influxPort'").text("Port");
$("label[for='influxDatabase'").text("Database name");
$("label[for='influxUsername'").text("Username");
$("label[for='influxPassword'").text("Password");
$("label[for='rule1value'").text("Emergency stop");
$("label[for='rule2value'").text("Internal BMS error");
$("label[for='rule3value'").text("Individual cell over voltage (mV)");
$("label[for='rule4value'").text("Cell under voltage (mV)");
$("label[for='rule5value'").text("Module over temperature (internal) °C");
$("label[for='rule6value'").text("Module under temperature (internal) °C");
$("label[for='rule7value'").text("Cell over temperature (external) °C");
$("label[for='rule8value'").text("Cell under temperature (external) °C");
$("label[for='rule9value'").text("Pack over voltage (mV)");
$("label[for='rule10value'").text("Pack under voltage (mV)");
$("label[for='rule11value'").text("Timer 2");
$("label[for='rule12value'").text("Timer 1");
$("label[for='defaultvalue'").text("Relay default");
$("label[for='relaytype'").text("Relay type");
$("label[for='CurrentMonEnabled'").text("Enabled");
$("label[for='modbusAddress'").text("Modbus address");
$("label[for='rs485baudrate'").text("Baud rate");
$("label[for='rs485databit'").text("Data bits");
$("label[for='rs485parity'").text("Data bits");
$("label[for='rs485stopbit'").text("Stop bits");
$("label[for='shuntmaxcur'").text("Shunt maximum current");
$("label[for='shuntmv'").text("Shunt output voltage (mV)");
$("label[for='cmvalid'").text("Values valid?");
$("label[for='cmtimestampage'").text("Last communication (milliseconds)");
$("label[for='cmwatchdog'").text("Watchdog counter");
$("label[for='cmtemperature'").text("Die temperature °C");
$("label[for='cmactualshuntmv'").text("Actual shunt mV reading");
$("label[for='cmcurrentlsb'").text("Current LSB size");
$("label[for='cmresistance'").text("Shunt resistance");
$("label[for='cmmodel'").text("Sensor model");
$("label[for='cmfirmwarev'").text("Firmware version");
$("label[for='cmfirmwaredate'").text("Firmware date");
$("label[for='cmRelayState'").text("Relay state");
$("label[for='cmTemperatureOverLimit'").text("Temperature over limit");
$("label[for='cmCurrentOverLimit'").text("Current over limit");
$("label[for='cmCurrentUnderLimit'").text("Current under limit");
$("label[for='cmVoltageOverLimit'").text("Voltage over limit");
$("label[for='cmVoltageUnderLimit'").text("Voltage under limit");
$("label[for='cmPowerOverLimit'").text("Power over limit");
$("label[for='cmcalibration'").text("Calibration");
$("label[for='cmtemplimit'").text("Temperature limit");
$("label[for='cmundervlimit'").text("Under voltage limit");
$("label[for='cmovervlimit'").text("Over voltage limit");
$("label[for='cmoverclimit'").text("Over current limit");
$("label[for='cmunderclimit'").text("Under current limit");
$("label[for='cmoverplimit'").text("Over power limit");
$("label[for='cmtempcoeff'").text("Temperature coefficient ppm/°C");
$("label[for='TempCompEnabled'").text("Temperature coefficient enabled");
$("label[for='cmTMPOL'").text("Relay Trigger: Temperature");
$("label[for='cmCURROL'").text("Relay Trigger: Current over");
$("label[for='cmCURRUL'").text("Relay Trigger: Current under");
$("label[for='cmVOLTOL'").text("Relay Trigger: Voltage over");
$("label[for='cmVOLTUL'").text("Relay Trigger: Voltage under");
$("label[for='cmPOL'").text("Relay Trigger: Power");
$("label[for='totalSeriesModules'").text("Number of series cells (eg. 8S)");
$("label[for='totalBanks'").text("Number of parallel banks (eg. 2P)");
$("label[for='NTPServer'").text("NTP Server");
$("label[for='NTPZoneHour'").text("Timezone (hour)");
$("label[for='NTPZoneMin'").text("Timezone (minute)");
$("label[for='NTPDST'").text("Daylight Saving Enabled");
$("label[for='Language'").text("Language");
$("label[for='VoltageHigh'").text("Graph voltage scale (high)");
$("label[for='VoltageLow'").text("Graph voltage scale (low)");
$("label[for='loggingEnabled'").text("SD card logging enabled");
$("label[for='loggingFreq'").text("Cell data logging frequency (seconds)");
$("#ap4").text("Remember, this product is free for personal use, if you would like to make a regular donation to keep the features and improvements flowing, use the Patreon link below.Even just a coffee / beer a month makes a difference.Thank you!  ");
$("#ap6").text("This is a DIY product / solution so don’t use this for safety critical systems or in any situation where there could be a risk to life.");
$("#ap7").text("There is no warranty, it may not work as expected or at all.");
$("#ap8").text("The use of this project is done so entirely at your own risk.It may involve electrical voltages which could kill - if in doubt, seek help.");
$("#ap8a").text("The use of this project may not be compliant with local laws or regulations - if in doubt, seek help.");
$("#ap10").text("This work is licensed under a Creative Commons Attribution - NonCommercial - ShareAlike 2.0 UK: England & Wales License.");
$("#hn").text("Host name: ");
$("#sdk").text("SDK Version: ");
$("#mfheap").text("Min free Heap: ");
$("#fheap").text("Free heap: ");
$("#heapz").text("Heap size: ");
$("#gc1").text("Configure all modules to use following parameters: ");
$("#ip2").text("For security, you will need to re - enter the password for the service(s) you want to enable or modify, before you save.");
$("#ip3").text("After changes are made, the controller will need to be rebooted, do this manually.");
$("#rt1").text("DIYBMS supports relay modules to safely disconnect chargers, contactors or consumers.The rules allow you to configure the relays for your situation.");
$("#rt2").text("Rules are processed from lowest priorty to highest(bottom up).Control the relays using the options.A value of "X" means don't care/leave at value defined by lower priority rules.");
$("#rt3").text("Rules are triggered when the relevant value meets or exceeds the 'trigger' value.The rule will only disable when the value then passes the 'reset' value.This can help prevent relay clatter and rules firing on / off rapidly.");
$("#rt4").text("'Timer 1' and 'Timer 2' rules allow timed operation, this rule is active when the number of minutes past midnight has been reached, for instance setting 'Timer 1' trigger to 495 and reset to 555 would switch on at 8: 15am and off at 9: 15am.This only works if connected to internet for regular time updates.");
$("#rt5").text("Minutes since midnight now is: ");
$("#rt6").text("Emergency stop is triggered by connector J1, once triggered controller needs to be reset to disable.");
$("#b1").text("Configure the MODBUS connection to the current monitor using the settings below.");
$("#b2").text("Configuration options for RS485 interface.Communication is half - duplex.");
$("#b3").text("Ensure the current shunt parameters match the data sheet for your particular shunt resistor.");
$("#b4").text("The current monitor uses a 40.96mV maximum scale, so shunt voltages over this will be scaled down proportionally.");
$("#b5").text("If you wish to use the relay control on the shunt monitor, set the parameters here.You should not normally need to change the calibration value.");
$("#b6").text("Current limit is for use whilst discharging the battery, under current limit is used when charging, so different discharge / charge current limits can be used.");
$("#b7").text("Temperature limit is based on the chip die temperature, which may not match the shunt temperature.Only positive temperature coefficient is supported.");
$("#b8").text("Relay triggers define which rules are used to trigger the relay into a closed state.");
$("#mb2").text("DIYBMS supports up to 100 modules in total.These modules can be split into banks to support parallel configurations.");
$("#mb3").text("Example: You have 16 cells configured as 8 in series and 2 in parallel(8S2P).");
$("#b9").text("Time is set via NTP, if your controller is not connected to the Internet.Time based rules will be incorrect.This does not automatically correct for daylight saving.");
$("#b10").text("Time now is ");
$("#b11").text("Controller can program modules and devices using the files below.Do not connect a device to be programmed before enabling programming mode.");
$("#sdcardmissing").text("SD card not installed");
$("#b12").text("Cell data and output states can be stored as log files using an SD card.");
$("#voltage0 span .x").text("Voltage 0:3.87V");
$("#range0 span .x").text("Range 0:0mV");
$("#voltage1 span .x").text("Voltage 1:");
$("#range1 span .x").text("Range 1:");
$("#voltage2 span .x").text("Voltage 2:");
$("#range2 span .x").text("Range 2:");
$("#voltage3 span .x").text("Voltage 3:");
$("#range3 span .x").text("Range 3:");
$("#voltage4 span .x").text("Voltage 4:");
$("#range4 span .x").text("Range 4:");
$("#voltage5 span .x").text("Voltage 5:");
$("#range5 span .x").text("Range 5:");
$("#voltage6 span .x").text("Voltage 6:");
$("#range6 span .x").text("Range 6:");
$("#voltage7 span .x").text("Voltage 7:");
$("#range7 span .x").text("Range 7:");
$("#voltage8 span .x").text("Voltage 8:");
$("#range8 span .x").text("Range 8:");
$("#voltage9 span .x").text("Voltage 9:");
$("#range9 span .x").text("Range 9:");
$("#voltage10 span .x").text("Voltage 10:");
$("#range10 span .x").text("Range 10:");
$("#voltage11 span .x").text("Voltage 11:");
$("#range11 span .x").text("Range 11:");
$("#voltage12 span .x").text("Voltage 12:");
$("#range12 span .x").text("Range 12:");
$("#voltage13 span .x").text("Voltage 13:");
$("#range13 span .x").text("Range 13:");
$("#voltage14 span .x").text("Voltage 14:");
$("#range14 span .x").text("Range 14:");
$("#voltage15 span .x").text("Voltage 15:");
$("#range15 span .x").text("Range 15:");
$("#current span .x").text("Current:");
$("#shuntv span .x").text("Shunt voltage:");
$("#power span .x").text("Power:");
$("#amphout span .x").text("Ah out:");
$("#amphin span .x").text("Ah in:");
$("#oos span .x").text("O.O.S errors:");
$("#badcrc span .x").text("CRC Errors:");
$("#ignored span .x").text("Ignored requests:");
$("#sent span .x").text("Packets sent:");
$("#received span .x").text("Packets rec'd:");
$("#roundtrip span .x").text("Roundtrip (ms):");
$("#uptime span .x").text("Uptime:");
$("#integration").text("Integration");
$("#currentmonitor").text("diyBMS Current Monitor");
$("#storage").text("Storage");
$("#avrprogrammer").text("AVR Programmer");
$("#about").text("About");
$("#home").text("Home");
$("#modules").text("Modules");
$("#settings").text("Settings");
$("#rules").text("Rules");
$("#more").text("More");
$("#view2d").text("2D");
$("#view3d").text("3D");
$("#b13").text("YouTube videos on installation and configuration");
